Repository thoth-station/talks, pull requests merged in 2021-11, with the labels that each got.

#22 Add slides for "Full-time Open Source" Hacktoberfest talk
  2021-11-03-hacktoberfest/hacktoberfest_monsterlab.pdf
Labels: approved, size/XS

#23 Add a link to termial-random article
  README.md
Labels: approved, size/XS

#24 Add RedHat Next slides
  2021-11-10-redhat-next/use-of-ai-in-devsecops.pdf
Labels: size/XS

#25 Add the team as approvers and reviewers
  OWNERS
Labels: size/S

#28 Add more Thoth articles
  README.md
Labels: approved, size/XS

#30 Enable prow in the repo with a basic pre-commit check
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  .prow.yaml
Labels: size/S
